# Generated by Django 4.2.7 on 2023-12-18 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(related_name='news', through='portal.PostCategory', to='portal.category'),
        ),
    ]
